server:
  port: 8090  # 指定当前服务的端口
  servlet:
    encoding:
      enabled: true # 大模型对话中文乱码处理
      force: true
      charset: utf-8
spring:
  application:
    name: springai_rag # 微服务名称
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      #      base-url: https://dashscope.aliyuncs.com/api/v1
      chat:
        options:
          model: glm-5.1
      embedding:
        options:
          model: text-embedding-v4  # 指定向量化模型
          text-type: document
    vectorstore:
      milvus:
        client:
          host: 127.0.0.1
          port: 19530
          # token: root:Milvus
        database-name: default
        collection-name: guide_store
        initialize-schema: true
        embedding-dimension: 1024
logging:
  pattern:
    console: "%-5level %logger - %msg%n" # 设置日志格式