server:
  port: 8081  # 指定当前服务的端口
  servlet:
    encoding:
      enabled: true # 大模型对话中文乱码处理
      force: true
      charset: utf-8
spring:
  application:
    name: springaialibaba01 # 微服务名称
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      base-url: https://dashscope.aliyuncs.com/api/v1
#      chat:
#        options:
#          model: qwen3.6-plus