server:
  port: 8086  # 指定当前服务的端口
  servlet:
    encoding:
      enabled: true # 大模型对话中文乱码处理
      force: true
      charset: utf-8
spring:
  application:
    name: springai_auto_memory # 微服务名称
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      #base-url: https://dashscope.aliyuncs.com/api/v1
      chat:
        options:
          model: glm-5.1
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always #自动创建ChatMemory存储的表结构 - 持久化对应的数据库表
            platform: mariadb #告诉框架当前数据库是 MariaDB/MySQL，
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: morningcat
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #确保每条 JDBC 连接都使用 utf8mb4 字符集并指定 utf8mb4_unicode_ci 排序
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci